// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonSkillsService.Infrastructure.Presistence;

namespace PersonSkillsService.Infrastructure.Migrations
{
    [DbContext(typeof(PersonSkillsContext))]
    [Migration("20210418173727_NewMigration")]
    partial class NewMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.HasSequence("EntityFrameworkHiLoSequence")
                .IncrementsBy(10);

            modelBuilder.Entity("PersonSkillsService.Domain.Aggregates.Persons.Person", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:HiLoSequenceName", "EntityFrameworkHiLoSequence")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.SequenceHiLo);

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DisplayName = "Виталий",
                            Name = "Виталий"
                        },
                        new
                        {
                            Id = 2L,
                            DisplayName = "Евгений",
                            Name = "Евгений"
                        },
                        new
                        {
                            Id = 3L,
                            DisplayName = "Екатерина",
                            Name = "Екатерина"
                        });
                });

            modelBuilder.Entity("PersonSkillsService.Domain.Aggregates.Skills.Skill", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte>("Level")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PersonId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Skill");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Level = (byte)10,
                            Name = "Сила",
                            PersonId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            Level = (byte)15,
                            Name = "Ум",
                            PersonId = 2L
                        },
                        new
                        {
                            Id = 3L,
                            Level = (byte)10,
                            Name = "Хитрость",
                            PersonId = 3L
                        });
                });

            modelBuilder.Entity("PersonSkillsService.Domain.Aggregates.Skills.Skill", b =>
                {
                    b.HasOne("PersonSkillsService.Domain.Aggregates.Persons.Person", "Person")
                        .WithMany("Skills")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("PersonSkillsService.Domain.Aggregates.Persons.Person", b =>
                {
                    b.Navigation("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
